using System.Collections.Generic;

namespace FlowTask_Backend
{
    /// <summary>
    /// The User class
    /// </summary>
    public class User
    {
        /// <summary>
        /// Primary Key
        /// </summary>
        public int UserID { get; private set; }

        /// <summary>
        /// The user's password --> This is hashed by the database.
        /// </summary>
        public string Password { get; private set; }

        /// <summary>
        /// Username field
        /// </summary>
        public string Username { get; private set; }

        //Set of text fields. Neither used nor very interesting.
        public string FirstName { get; private set; }
        public string LastName { get; private set; }
        public string Email { get; private set; }

        /// <summary>
        /// A list of the user's tasks. This is generated by the DB.
        /// </summary>
        public List<Task> Tasks { get; private set; }

        /// <summary>
        /// Create a user with the given parameters.
        /// To be used by DB only.
        /// </summary>
        /// <param name="userID"></param>
        /// <param name="password"></param>
        /// <param name="username"></param>
        /// <param name="firstName"></param>
        /// <param name="lastName"></param>
        /// <param name="email"></param>
        public User(int userID, string password, string username, string firstName, string lastName, string email)
        {
            UserID = userID;
            Password = password.Trim();
            Username = username.ToLowerInvariant().Trim();
            FirstName = firstName.Trim();
            LastName = lastName.Trim();
            Email = email.Trim();
            Tasks = new List<Task>();
        }

        /// <summary>
        /// Create a user without a UserID.
        /// </summary>
        /// <param name="password"></param>
        /// <param name="username"></param>
        /// <param name="firstName"></param>
        /// <param name="lastName"></param>
        /// <param name="email"></param>
        public User(string password, string username, string firstName, string lastName, string email)
        {
            Password = password.Trim();
            Username = username.ToLowerInvariant().Trim();
            FirstName = firstName.Trim();
            LastName = lastName.Trim();
            Email = email.Trim();
            Tasks = new List<Task>();
        }

    }
}
